export const user = [
    {
      id: 1,
      gender: "female",
      fname: "Patience",
      lname: "Patience",
      email: "benji@123",
      contact: "123456789",
    },
    {
      id: 2,
      gender: "male",
      fname: "Benjamin",
      lname: "Patience",
      email: "benji@123",
      contact: "123456789",
    },
    {
      id: 3,
      gender: "female",
      fname: "Benjamin",
      lname: "Nyankson",
      email: "benji@123",
      contact: "123456789",
    },
    {
      id: 4,
      gender: "male",
      fname: "Yakubu",
      lname: "Yakubu",
      email: "akubu@123",
      contact: "123456789",
    },
    {
      id: 5,
      gender: "male",
      fname: "Benjamin",
      lname: "Benjamin",
      email: "benji@123",
      contact: "123456789",
    },
    {
      id: 6,
      gender: "female",
      fname: "Benjamin",
      lname: "Benjamin",
      email: "benji@123",
      contact: "0241216747",
    },
  ];